name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r parser/requirements.txt

      - name: Run flake8
        run: |
          flake8 parser/src/parser.py webapp/app.py --max-line-length=100
